export const ROUTES = {
  login: '/',
  register: '/register',
  terms: '/terms',
  privacy: '/privacy',
  home: '/home',
  talent: '/talents/profile',
  knowledge: '/discover/problems',
  experiences: '/discover/experiences',
  filtered: '/discover/problems/results',
  inquiries: '/inquiries',
  directChat: '/messages/direct',
  profile: '/profile',
  accountSettings: '/profile/settings',
  wallet: '/profile/wallet',
  certs: '/profile/certifications',
  certWork: '/profile/certifications/work',
  certExperience: '/profile/certifications/experiences',
  certBasicApply: '/profile/certifications/basic/apply',
  certExperienceApply: '/profile/certifications/experiences/apply',
  feedback: '/profile/feedback',
  faq: '/profile/faq',
  business: '/profile/business',
  customerService: '/profile/customer-service',
  notices: '/notices',
};

export const PATH_TO_SCREEN = Object.fromEntries(
  Object.entries(ROUTES).map(([screen, route]) => [route, screen]),
);
