import { useEffect, useMemo, useState } from 'react';
import { MessagesSquare, Percent, Settings2 } from 'lucide-react';
import { adminApi } from '../../api/adminApi.js';
import { useAdminAccess } from '../../app/AdminAccessContext.jsx';
import { message } from '../../components/feedback/message.js';
import './AppSettingsPage.css';

const previewAmount = 100;
const groups = [
  { key: 'features', title: '功能开关', description: '紧急停用某项入口时使用。关闭后后端也会拒绝新请求，不只是隐藏 App 按钮。', example: '支付渠道故障时，可临时关闭充值；语音异常时，可只关闭语音而不影响文字交流。', fields: [
    ['experiencePublishEnabled','发布经历','允许提交新经历，已有经历仍可查看。','switch'],['inquiryEnabled','发起询问','允许创建新询问，已经开始的询问不受影响。','switch'],['voiceCallEnabled','语音通话','允许在询问中发起新的语音通话。','switch'],['experienceTipEnabled','经历打赏','允许对已结束询问对应的经历发起打赏。','switch'],['rechargeEnabled','支付宝充值','允许创建新的充值订单。','switch'],['withdrawalEnabled','支付宝提现','允许提交新的提现申请。','switch'],
  ]},
  { key: 'money', title: '资金与奖励', description: '控制押金、收入冻结期、提现限制和首次发布奖励。所有收入统一使用上方劳动报酬服务费率。', example: 'Android 劳动报酬费率设为5%，用户通过 Android 收到10元语音收入、打赏或活动奖励，均按5%计算服务费。', fields: [
    ['inquiryDepositAmount','询问占位押金','待处理询问达到免费数量后，新询问需要冻结的金额；结束或拒绝后退回。','money','元'],['freePendingInquiryLimit','免费待处理询问数','有多少条“待对方同意”的询问时，下一条开始收押金。','number','条'],['incomeHoldHours','收入冻结时间','劳动报酬和打赏到账后，经过该时间才可提现。','number','小时'],['withdrawalMinAmount','单笔提现最低金额','低于此金额不能提交提现。','money','元'],['withdrawalMaxAmount','单笔提现最高金额','单次提现不能超过此金额。','money','元'],['withdrawalDailyLimit','每日提现总上限','一个用户自然日内累计申请金额的上限。','money','元'],['payoutAccountCooldownHours','支付宝授权冷静期','首次授权或变更支付宝后，需要等待多久才能提现。','number','小时'],['tipPresetAmounts','打赏快捷金额','App 打赏弹窗展示的快捷选项，使用英文逗号分隔。','list','元'],['tipMaxAmount','自定义打赏上限','用户输入的单次打赏金额上限。','number','元'],['firstExperienceRewardEnabled','首次发布奖励','是否对首次审核通过的经历发放一次奖励。','switch'],['firstExperienceRewardAmount','首次发布奖励金额','每个用户最多领取一次，并按劳动报酬服务费率计算实际到账。','money','元'],['firstExperienceRewardStartAt','奖励开始时间','留空表示不限制开始时间。','datetime'],['firstExperienceRewardEndAt','奖励结束时间','留空表示不限制结束时间。','datetime'],
  ]},
  { key: 'communication', title: '文字与语音', description: '控制询问的免费文字额度、语音计费边界、等待和断线恢复时间。', example: '“增加额度所需通话时长”设为300秒、“增加文字额度”设为50，双方一次正常通话满5分钟后，各增加50条文字额度。', fields: [
    ['initialTextMessageLimit','初始文字额度','询问被接受后，双方一开始各自可发送的正常文字消息数。','number','条/人'],['textMessageMaxLength','单条文字上限','一条普通聊天消息最多允许输入的字数。','number','字'],['voiceRewardSeconds','增加额度所需通话时长','单次正常语音达到此时长，才增加文字额度。','number','秒'],['voiceRewardMessages','通话后增加文字额度','达到上方时长后，双方各增加的文字消息数量。','number','条/人'],['voiceRingTimeoutSeconds','语音呼叫等待时间','对方未在该时间内接听，本次呼叫结束并退回冻结金额。','number','秒'],['voiceReconnectTimeoutSeconds','语音断线重连时间','通话中断后允许恢复连接的最长时间；超时只结束本次通话。','number','秒'],['inquiryResponseTimeoutHours','新询问等待时间','回答方未在该时间内接受，询问自动结束并退回押金。','number','小时'],['inquiryMaxDurationDays','单次询问最长时间','从接受询问开始计算，到期系统结束询问，语音也不能突破该期限。','number','天'],['hourlyRateMin','每小时费用下限','用户设置语音费用时可填写的最低值。','number','元/小时'],['hourlyRateMax','每小时费用上限','用户设置语音费用时可填写的最高值。','number','元/小时'],
  ]},
  { key: 'experience', title: '经历与首页', description: '控制经历提交规格和首页每次读取数量。修改字数限制只影响之后的提交，不会截断历史内容。', example: '首页每页设为20，App 首次只请求20条经历，继续下拉时再请求下一页，避免一次传输大量用户未查看的数据。', fields: [
    ['maxUnapprovedExperiences','未通过经历数量上限','审核中或被退回的经历达到该数量后，需要先处理现有内容。','number','条'],['experienceTitleMaxLength','经历标题上限','发布经历时主标题允许的最大字数。','number','字'],['experienceDescriptionMaxLength','经历叙述上限','发布经历时文字叙述允许的最大字数。','number','字'],['proofArchiveMaxBytes','证明压缩包上限','单个证明资料压缩包允许的最大容量。','megabytes','MB'],['homePageSize','首页每页数量','首页每次分页请求的经历卡片数量。','number','条'],
  ]},
];

export default function AppSettingsPage() {
  const { can } = useAdminAccess();
  const [fee, setFee] = useState(null); const [rates, setRates] = useState({android:'',ios:''});
  const [capacity, setCapacity] = useState(null); const [limits, setLimits] = useState({questioner:'1',answerer:'3'});
  const [settings, setSettings] = useState(null); const [persistedSettings, setPersistedSettings] = useState(null); const [saving, setSaving] = useState('');
  useEffect(() => { if(can('PLATFORM_FEE_VIEW')) adminApi.platformFee().then(v=>{setFee(v);setRates({android:fmt(v.androidRatePercent),ios:fmt(v.iosRatePercent)});}).catch(showError); if(can('INQUIRY_CAPACITY_VIEW')) adminApi.inquiryCapacity().then(v=>{setCapacity(v);setLimits({questioner:String(v.questionerLimit),answerer:String(v.answererLimit)});}).catch(showError); if(can('APP_GLOBAL_SETTING_VIEW')) adminApi.appGlobalSettings().then(applyGlobal).catch(showError); }, []);
  const applyGlobal = (v) => {const normalized=globalFormValues(v);setSettings(normalized);setPersistedSettings(normalized);};
  const save = async (key, task, text) => { try{setSaving(key);await task();message.success(text);}catch(e){showError(e);}finally{setSaving('');} };
  const saveFee = (e) => {e.preventDefault(); const a=validRate(rates.android,'Android'),i=validRate(rates.ios,'iOS');if(a==null||i==null)return;save('fee',async()=>{const v=await adminApi.updatePlatformFee(a,i);setFee(v);setRates({android:fmt(v.androidRatePercent),ios:fmt(v.iosRatePercent)});},'服务费率已更新');};
  const saveCapacity = (e) => {e.preventDefault();const q=validLimit(limits.questioner,'询问人'),a=validLimit(limits.answerer,'被询问人');if(q==null||a==null)return;save('capacity',async()=>{const v=await adminApi.updateInquiryCapacity(q,a);setCapacity(v);setLimits({questioner:String(v.questionerLimit),answerer:String(v.answererLimit)});},'同时交流上限已更新');};
  const saveGlobal = (e, group) => {e.preventDefault();const draft={...persistedSettings};group.fields.forEach(([key])=>{draft[key]=settings[key]});const body=globalApiValues(draft);save(`global-${group.key}`,async()=>{const normalized=globalFormValues(await adminApi.updateAppGlobalSettings(body));setPersistedSettings(normalized);setSettings(current=>{const next={...current};group.fields.forEach(([key])=>{next[key]=normalized[key]});return next;});},`${group.title}已更新`);};
  const preview=useMemo(()=>({android:previewAmount*(Number(rates.android)||0)/100,ios:previewAmount*(Number(rates.ios)||0)/100}),[rates]);
  return <><div className="page-title"><div><h1>App全局设置</h1><p>集中维护全局业务规则；每项均说明用途、影响范围和使用场景</p></div></div><div className="app-settings-sections">
    {can('PLATFORM_FEE_VIEW')&&<form className="app-setting-section" onSubmit={saveFee}><Heading icon={Percent} title="劳动报酬服务费" description="语音劳动报酬、打赏和活动奖励等所有可提现收入，统一按产生收入的 App 平台计算。费率会随交易保存，之后修改不会追溯历史交易。" example="Android 费率5%，用户通过 Android 获得100元语音收入、打赏或活动奖励时，均扣5元服务费，实际收入95元。"/><div className="app-setting-grid">{['android','ios'].map(k=><SimpleField key={k} label={`${k==='android'?'Android':'iOS'}费率`} help="用于该平台产生的所有可提现收入。" value={rates[k]} suffix="%" disabled={!can('PLATFORM_FEE_EDIT')} onChange={v=>setRates(x=>({...x,[k]:v}))} note={`收入100元：服务费${preview[k].toFixed(2)}元，实际收入${(100-preview[k]).toFixed(2)}元`}/>)}</div>{can('PLATFORM_FEE_EDIT')&&<button className="primary app-setting-save" disabled={saving==='fee'}>{saving==='fee'?'保存中':'保存服务费'}</button>}</form>}
    {can('INQUIRY_CAPACITY_VIEW')&&<form className="app-setting-section" onSubmit={saveCapacity}><Heading icon={MessagesSquare} title="同时交流人数" description="限制一个账号同一时间占用的交流名额。系统会在发起和接受时读取最新配置。" example="询问人设为1、被询问人设为3：一个用户同时只能向1人进行交流，但最多可同时接受3人的询问。"/><div className="app-setting-grid"><SimpleField label="询问人上限" help="同一用户作为提问者，同时处于交流中的询问数量。" value={limits.questioner} suffix="人" disabled={!can('INQUIRY_CAPACITY_EDIT')} onChange={v=>setLimits(x=>({...x,questioner:v}))}/><SimpleField label="被询问人上限" help="同一用户作为回答者，同时处于交流中的询问数量。" value={limits.answerer} suffix="人" disabled={!can('INQUIRY_CAPACITY_EDIT')} onChange={v=>setLimits(x=>({...x,answerer:v}))}/></div>{capacity?.updatedAt&&<small className="app-setting-updated">最近更新：{new Date(capacity.updatedAt).toLocaleString('zh-CN')}</small>}{can('INQUIRY_CAPACITY_EDIT')&&<button className="primary app-setting-save" disabled={saving==='capacity'}>{saving==='capacity'?'保存中':'保存人数上限'}</button>}</form>}
    {can('APP_GLOBAL_SETTING_VIEW')&&settings&&<div className="app-global-form">{groups.map(g=><form className="app-setting-section" key={g.key} onSubmit={e=>saveGlobal(e,g)}><Heading icon={Settings2} title={g.title} description={g.description} example={g.example}/><div className="app-setting-grid app-global-grid">{g.fields.map(([key,label,help,type,suffix])=><ConfigField key={key} label={label} help={help} type={type} suffix={suffix} value={settings[key]} disabled={!can('APP_GLOBAL_SETTING_EDIT')} onChange={v=>setSettings(x=>({...x,[key]:v}))}/>)}</div>{can('APP_GLOBAL_SETTING_EDIT')&&<div className="app-setting-group-footer"><span>保存后影响后续业务操作，已经创建的订单仍按创建时保存的规则执行。</span><button className="primary app-setting-save" disabled={saving===`global-${g.key}`}>{saving===`global-${g.key}`?'保存中':`保存${g.title}`}</button></div>}</form>)}</div>}
  </div></>;
}
function Heading({icon:Icon,title,description,example}){return <div className="app-setting-heading"><i><Icon/></i><div><h2>{title}</h2><p>{description}</p><p className="app-setting-example"><b>使用场景：</b>{example}</p></div></div>}
function SimpleField({label,help,value,suffix,disabled,onChange,note}){return <label className="app-config-card"><b>{label}</b><span>{help}</span><div className="app-setting-input"><input value={value} disabled={disabled} inputMode="decimal" onChange={e=>onChange(e.target.value)}/><em>{suffix}</em></div>{note&&<small>{note}</small>}</label>}
function ConfigField({label,help,type,suffix,value,disabled,onChange}){if(type==='switch')return <label className="app-config-card app-config-switch"><div><b>{label}</b><span>{help}</span></div><input type="checkbox" checked={Boolean(value)} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>;return <label className="app-config-card"><b>{label}</b><span>{help}</span><div className="app-setting-input"><input type={type==='datetime'?'datetime-local':'text'} value={value??''} disabled={disabled} inputMode={['number','money','percent','megabytes'].includes(type)?'decimal':undefined} onChange={e=>onChange(e.target.value)}/><em>{type==='percent'?'%':suffix}</em></div></label>}
function globalFormValues(v){return {...v,tipPresetAmounts:(v.tipPresetAmounts||[]).join(','),proofArchiveMaxBytes:fmt(Number(v.proofArchiveMaxBytes)/1024/1024),firstExperienceRewardStartAt:localTime(v.firstExperienceRewardStartAt),firstExperienceRewardEndAt:localTime(v.firstExperienceRewardEndAt)}}function globalApiValues(v){return {...v,tipPresetAmounts:String(v.tipPresetAmounts).split(',').map(x=>Number(x.trim())).filter(Number.isInteger),proofArchiveMaxBytes:Math.round(Number(v.proofArchiveMaxBytes)*1024*1024),firstExperienceRewardStartAt:v.firstExperienceRewardStartAt||null,firstExperienceRewardEndAt:v.firstExperienceRewardEndAt||null,updatedByAdminId:null,updatedAt:null}}function validRate(v,l){const n=Number(v);if(!Number.isFinite(n)||n<0||n>99){message.warning(`${l}费率必须在0%至99%之间`);return null}return n}function validLimit(v,l){const n=Number(v);if(!Number.isInteger(n)||n<1||n>20){message.warning(`${l}上限必须在1至20之间`);return null}return n}function fmt(v){const n=Number(v||0);return Number.isInteger(n)?String(n):String(n).replace(/0+$/,'').replace(/\.$/,'')}function localTime(v){return v?String(v).slice(0,16):''}function showError(e){message.error(e.message)}
